[build]
  command = """
  cd hinglish-caption-pro && npm install && npm run build &&
  mkdir -p ../site/caption && cp -r dist/* ../site/caption/ &&
  cd ../hinglish-studio-ai && npm install && npm run build &&
  mkdir -p ../site/studio && cp -r dist/* ../site/studio/ &&
  cd ../artix-studio-ai && npm install && npm run build &&
  mkdir -p ../site/artix && cp -r dist/* ../site/artix/
  """
  publish = "site"


[[redirects]]
from = "/caption/*"
to = "/hinglish-caption-pro/dist/:splat"
status = 200

[[redirects]]
from = "/studio/*"
to = "/hinglish-studio-ai/dist/:splat"
status = 200

[[redirects]]
from = "/artix/*"
to = "/artix-studio-ai/dist/:splat"
status = 200
